### ISSUE TITLE
[Improvement] - Improve navigation

### ISSUE THREAD

**Issue by omeansteam** [rogue-dev-studio/omeans-team.github#5]
Improve navigation 

From below : 
![image](https://github.com/omeans-team/omeans-team.github.io/assets/160024389/159215f1-d9eb-464c-958b-a72ebeda4a31)
![image](https://github.com/omeans-team/omeans-team.github.io/assets/160024389/ed6829b5-57dd-4d3f-9fa7-60db3300ed8a)

To like below : 
![image](https://github.com/omeans-team/omeans-team.github.io/assets/160024389/f9e83cd6-1810-4c49-8fc4-12335301be65)
![image](https://github.com/omeans-team/omeans-team.github.io/assets/160024389/e4df4c66-6563-4231-8f94-0eac8b636669)

**Comment by rogue-dev-studio** [comment]
![image](https://github.com/omeans-team/omeans-team.github.io/assets/47584746/0e03fd05-dfcc-454c-ad41-1438df7e3818)

- dynamic link internal and external 
- add data navigation _data/navigation.yml
- maintain time ago when not found
